kind: Deployment
apiVersion: apps/v1
metadata:
  name: PREFIXdirserver
  labels:
    app: dirserver
spec:
  replicas: 1
  selector:
    matchLabels:
     app: dirserver
  template:
    metadata:
      labels:
        app: PREFIXdirserver
    spec:
      containers:
      - name: PREFIXdirserver
        image: gcr.io/PROJECT/PREFIXdirserver
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /dirserver-logs
          name: PREFIXdirserver
      volumes:
      - name: PREFIXdirserver
        gcePersistentDisk:
          pdName: PREFIXdirserver
          fsType: ext4
