kind: Deployment
apiVersion: apps/v1
metadata:
  name: PREFIXfrontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
     app: frontend
  template:
    metadata:
      labels:
        app: PREFIXfrontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT/PREFIXfrontend
        ports:
        - containerPort: 80
        - containerPort: 443
