kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: PREFIXhostserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: PREFIXhostserver
    spec:
      containers:
      - name: PREFIXhostserver
        image: gcr.io/PROJECT/PREFIXhostserver
        ports:
        - containerPort: 443
