kind: Deployment
apiVersion: apps/v1
metadata:
  name: PREFIXhostserver
  labels:
    app: hostserver
spec:
  replicas: 1
  selector:
    matchLabels:
     app: hostserver
  template:
    metadata:
      labels:
        app: PREFIXhostserver
    spec:
      containers:
      - name: PREFIXhostserver
        image: gcr.io/PROJECT/PREFIXhostserver
        ports:
        - containerPort: 80
        - containerPort: 443
