kind: Deployment
apiVersion: apps/v1
metadata:
  name: PREFIXkeyserver
  labels:
    app: keyserver
spec:
  replicas: 1
  selector:
    matchLabels:
     app: keyserver
  template:
    metadata:
      labels:
        app: PREFIXkeyserver
    spec:
      containers:
      - name: PREFIXkeyserver
        image: gcr.io/PROJECT/PREFIXkeyserver
        ports:
        - containerPort: 80
        - containerPort: 443
