kind: Deployment
apiVersion: apps/v1
metadata:
  name: PREFIXstoreserver
  labels:
    app: storeserver
spec:
  replicas: 1
  selector:
    matchLabels:
     app: storeserver
  template:
    metadata:
      labels:
        app: PREFIXstoreserver
    spec:
      containers:
      - name: PREFIXstoreserver
        image: gcr.io/PROJECT/PREFIXstoreserver
        ports:
        - containerPort: 80
        - containerPort: 443
